### ISSUE TITLE
Classification tasks are sometimes not recognized

### ISSUE THREAD

**Issue by andreash0** [dandls/counterfactuals#29] opened 2023-03-22 13:06 UTC
I haven't had time to investigate this in detail, but it seems that there are cases where our classification methods do not correctly recognize classification tasks:

``` r
library(counterfactuals)
library(iml)
library(dplyr)
library(tidymodels)

data(german, package = "rchallenge")

credit = german[, c("duration", "amount", "purpose", "age",
                    "employment_duration", "housing", "number_credits", "credit_risk")]

x_interest = credit[998L,]
rf = rand_forest(mode = "classification", engine = "randomForest") %>%
  fit(credit_risk ~ ., data = credit[-998L,])

pred = Predictor$new(model = rf, data = credit[-998L,], y = "credit_risk")
nice_classif = MOCClassif$new(pred)
#> Error in super$initialize(predictor, lower, upper, distance_function): MOCClassif only works for classification tasks.
```

However, if we explicitely set the `prob` argument in the `Predictor$init()` method, it works:

``` r
library(counterfactuals)
library(iml)
library(dplyr)
library(tidymodels)
data(german, package = "rchallenge")

credit = german[, c("duration", "amount", "purpose", "age",
                    "employment_duration", "housing", "number_credits", "credit_risk")]

x_interest = credit[998L,]
rf = rand_forest(mode = "classification", engine = "randomForest") %>%
  fit(credit_risk ~ ., data = credit[-998L,])

pred = Predictor$new(model = rf, data = credit[-998L,], y = "credit_risk", type = "prob")
nice_classif = MOCClassif$new(pred)
```

**Comment by dandls** [comment] 2023-03-22 16:06
This seems to be an issue of the `iml` Package. 
If `pred$task == "unknown"`, we call these [two lines](https://github.com/dandls/counterfactuals/blob/main/R/CounterfactualMethod.R#L34-L35). 
Within `iml`, the function `iml:::inferTaskFromPrediction()` is called, which identifies the task falsely as a `regression` task and then `pred$task = "regression" is set. This triggers the "MOCClassif only works for classification" error.

Here is an example without using the `counterfactuals ` package: 
```
library(iml)
library(tidymodels)

data(german, package = "rchallenge")
credit = german[, c("duration", "amount", "purpose", "age",
  "employment_duration", "housing", "number_credits", "credit_risk")]

# tidymodels
rf = rand_forest(mode = "classification", engine = "randomForest") %>%
  fit(credit_risk ~ ., data = credit)

pred = Predictor$new(model = rf, data = credit, y = "credit_risk")
pred$task
pred$task = NULL
pred$predict(credit[c(1, 2),])
pred$task
iml:::inferTaskFromPrediction(prediction = pred$predict(credit[c(1, 2),]))
```

**Comment by dandls** [comment] 2024-09-21 09:12
I transferred this issue now to the iml package, see giuseppec/iml#216.

**Comment by dandls** [comment] 2024-09-21 09:12
Closed, see above.

**Comment by dandls** [comment] 2024-09-21 09:13
I transferred this issue now to the iml package, see giuseppec/iml#216.

**Comment by dandls** [comment] 2024-09-21 09:14
I transferred this issue now to the iml package, see giuseppec/iml#216.

**Closed by dandls** 2024-09-21 09:14 UTC
